export const signInStyles = {
	body: {
		width: '100%',
		height: '100vh',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#f2f2f2',
	},
	folder: {
		width: '100%',
		maxWidth: 1200,
		height: 320,
		display: 'flex',
	},
	presentation: {
		width: '55%',
		height: '100%',
		backgroundColor: '#1d9bf0',
		borderRadius: '10px 0px 0px 10px',
		py: 10,
		px: 3,
		color: 'white',
		display: 'flex',
		flexDirection: 'column',
		gap: 1,
	},
	signIn: {
		width: '45%',
		height: '100%',
		backgroundColor: 'white',
		borderRadius: '0px 10px 10px 0px',
		px: 10,
		py: 4,
		color: '#888',
	},
};
